namespace ScreenshotCollector.Models;

public sealed class SceneDocument
{
    public string Format { get; set; } = "MuseBox.Scene";
    public int Version { get; set; } = 2;
    public string Name { get; set; } = "未命名";
    public BoardViewport Viewport { get; set; } = new();
    public List<BoardItem> Images { get; set; } = new();
    public List<BoardTextItem> Texts { get; set; } = new();
    public List<BoardDrawingItem> Drawings { get; set; } = new();
    public List<BoardGroup> Groups { get; set; } = new();
    public List<SceneAsset> Assets { get; set; } = new();
    public List<GifSceneState> Gifs { get; set; } = new();
    public DrawerCover? Cover { get; set; }
    public string ThumbnailPng { get; set; } = string.Empty;
}

public sealed record SceneAsset(string Id, string Hash, string Extension, int Width, int Height);
public sealed record SceneBinding(string DrawerId, string FilePath, long SavedRevision, string FileHash);
public sealed record SceneSnapshot(SceneDocument Document, IReadOnlyDictionary<string, string> AssetPaths, long Revision);
public sealed record GifSceneState(string ItemId, double Speed, bool IsPlaying, int FrameIndex);

public sealed class PreparedScene : IDisposable
{
    public SceneDocument Document { get; }
    public IReadOnlyDictionary<string, string> AssetPaths { get; }
    public string FileHash { get; }
    private readonly string _temporaryDirectory;
    internal PreparedScene(SceneDocument document, Dictionary<string, string> paths, string hash, string directory)
        => (Document, AssetPaths, FileHash, _temporaryDirectory) = (document, paths, hash, directory);
    public void Dispose()
    {
        // This directory is freshly generated by SceneFileService, never archive supplied.
        try { Directory.Delete(_temporaryDirectory, true); } catch (IOException) { } catch (UnauthorizedAccessException) { }
    }
}
